### ISSUE TITLE
Crash with 1.1.0 preview

### ISSUE THREAD

**Issue by markus456** [signal18/replication-manager#159]
```
Apr 24 14:13:39 galera-000 systemd[1]: replication-manager.service: main process exited, code=exited, status=2/INVALIDARGUMENT
Apr 24 14:13:39 galera-000 replication-manager[7659]: panic: runtime error: invalid memory address or nil pointer dereference
Apr 24 14:13:39 galera-000 replication-manager[7659]: [signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0xa08556]
Apr 24 14:13:39 galera-000 replication-manager[7659]: goroutine 44911 [running]:
Apr 24 14:13:39 galera-000 replication-manager[7659]: github.com/tanji/replication-manager/cluster.(*ServerMonitor).rejoin(0xc4202e4580, 0xc4203290e0, 0x2f)
Apr 24 14:13:39 galera-000 replication-manager[7659]: /home/tanj/go/src/github.com/tanji/replication-manager/cluster/monitor.go:715 +0x166
Apr 24 14:13:39 galera-000 replication-manager[7659]: github.com/tanji/replication-manager/cluster.(*ServerMonitor).check(0xc4202e4580, 0xc420406fb0)
Apr 24 14:13:39 galera-000 replication-manager[7659]: /home/tanj/go/src/github.com/tanji/replication-manager/cluster/monitor.go:282 +0x1b3f
Apr 24 14:13:39 galera-000 replication-manager[7659]: created by github.com/tanji/replication-manager/cluster.(*Cluster).Run
Apr 24 14:13:39 galera-000 replication-manager[7659]: /home/tanj/go/src/github.com/tanji/replication-manager/cluster/cluster.go:164 +0x33c
Apr 24 14:13:39 galera-000 systemd[1]: Unit replication-manager.service entered failed state.
Apr 24 14:13:39 galera-000 systemd[1]: replication-manager.service failed.
```
Log:
[replication-manager.txt](https://github.com/tanji/replication-manager/files/952022/replication-manager.txt)

Config:
[config.txt](https://github.com/tanji/replication-manager/files/952029/config.txt)

Two node setup with a master and a slave. Kill slave, kill master, replication manager crashed.

**Comment by svaroqui** [comment]
Close in nightly build thanks for the record
