### ISSUE TITLE
config-group command line argument does not work on failover

### ISSUE THREAD

**Issue by vfxcode** [signal18/replication-manager#186]
If there are two (or more?) clusters defined in config.toml in topology and switchover everything seems to be working as expected. That is, with --config-group it (seems to) correctly use the valid configuration.
In failover mode it seems to either fail or use the first config-group it encounters.

To duplicate use a sample config:
```
[Default]
title = "emptytest"
user = "user:pass"
rpluser = "repl:repl"
hosts = "host1.test.com,host2.test.com"
ignore-servers = ""
prefmaster = "host1.test.com"
.....
[validcluster]
title          = "whatever"
user           = "repl-manager:repl-manager"
rpluser        = "repl:repl"
hosts          = "valid1.test.com,valid2.test.com"
ignore-servers = ""
prefmaster     = "valid1.test.com"
....
```

```
# replication-manager  --config-group validcluster failover
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0xa2e2f3]

goroutine 1 [running]:
github.com/tanji/replication-manager/cluster.(*ServerMonitor).Refresh(0xc4203f4380, 0x0, 0x0)
	/home/tanj/go/src/github.com/tanji/replication-manager/cluster/monitor.go:321 +0xb3
github.com/tanji/replication-manager/cluster.(*Cluster).TopologyDiscover(0xc4203f8700, 0xd8d765, 0x1c)
	/home/tanj/go/src/github.com/tanji/replication-manager/cluster/topology.go:173 +0x193
main.glob..func9(0x136c6c0, 0xc420299ea0, 0x0, 0x2)
	/home/tanj/go/src/github.com/tanji/replication-manager/repmgr.go:229 +0x1df
github.com/tanji/replication-manager/vendor/github.com/spf13/cobra.(*Command).execute(0x136c6c0, 0xc420299d00, 0x2, 0x2, 0x136c6c0, 0xc420299d00)
	/home/tanj/go/src/github.com/tanji/replication-manager/vendor/github.com/spf13/cobra/command.go:648 +0x234
github.com/tanji/replication-manager/vendor/github.com/spf13/cobra.(*Command).ExecuteC(0x136ba00, 0x11, 0x1, 0x0)
	/home/tanj/go/src/github.com/tanji/replication-manager/vendor/github.com/spf13/cobra/command.go:734 +0x339
github.com/tanji/replication-manager/vendor/github.com/spf13/cobra.(*Command).Execute(0x136ba00, 0x0, 0x0)
	/home/tanj/go/src/github.com/tanji/replication-manager/vendor/github.com/spf13/cobra/command.go:693 +0x2b
main.main()
	/home/tanj/go/src/github.com/tanji/replication-manager/main.go:165 +0x31
# 
```

I am using the 1.1.2 version from the released package here on github.

**Comment by tanji** [comment]
Hi @vfxcode, have you tried failover using the monitor mode? It is not really recommended to use the CLI, as there is no monitoring at all.

I will look at this issue nonetheless.

**Comment by tanji** [comment]
Try one of these packages, I fixed the error described above:
http://ci.signal18.io/mrm/builds/1.1/

**Comment by vfxcode** [comment]
I can still make it crash. Even in monitor mode.
I suspect this time its because the domain names for the default cluster do not exist...
The trully valid cluster seems to work ok.

```
# replication-manager --config-group Default topology
INFO[2017-10-12T12:13:35+03:00] Server [0] valid1.skroutz.gr Failed           cluster=Default
INFO[2017-10-12T12:13:35+03:00] Server [1] valid2.skroutz.gr Failed           cluster=Default
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0xa1478a]

goroutine 1 [running]:
github.com/signal18/replication-manager/cluster.(*Cluster).Close(0xc4202d1800)
	/var/jenkins_home/workspace/go/src/github.com/signal18/replication-manager/cluster/cluster.go:616 +0x4a
main.glob..func14(0x137ab00, 0xc4202b1560, 0x0, 0x2)
	/var/jenkins_home/workspace/go/src/github.com/signal18/replication-manager/repmgr.go:280 +0x2d
github.com/signal18/replication-manager/vendor/github.com/spf13/cobra.(*Command).execute(0x137ab00, 0xc4202b13c0, 0x2, 0x2, 0x137ab00, 0xc4202b13c0)
	/var/jenkins_home/workspace/go/src/github.com/signal18/replication-manager/vendor/github.com/spf13/cobra/command.go:655 +0x35b
github.com/signal18/replication-manager/vendor/github.com/spf13/cobra.(*Command).ExecuteC(0x1379a00, 0x11, 0x1, 0x0)
	/var/jenkins_home/workspace/go/src/github.com/signal18/replication-manager/vendor/github.com/spf13/cobra/command.go:734 +0x339
github.com/signal18/replication-manager/vendor/github.com/spf13/cobra.(*Command).Execute(0x1379a00, 0x0, 0x0)
	/var/jenkins_home/workspace/go/src/github.com/signal18/replication-manager/vendor/github.com/spf13/cobra/command.go:693 +0x2b
main.main()
	/var/jenkins_home/workspace/go/src/github.com/signal18/replication-manager/main.go:166 +0x31
```

Failover through the monitor interface seems to work correctly 
Through the cli, however, it seems to always use the hosts of the default group (or a group that is the first defined in the toml config file).

For example
```
# replication-manager --config-group stefbtest switchover
INFO[2017-10-12T12:29:00+03:00] [stefbtest] INFO : Starting master switch    
INFO[2017-10-12T12:29:00+03:00] Checking long running updates on master 10    cluster=stefbtest
INFO[2017-10-12T12:29:00+03:00] Flushing tables on master db.stefbdb.st.skroutz.gr  cluster=stefbtest
INFO[2017-10-12T12:29:00+03:00] Electing a new master                         cluster=stefbtest
INFO[2017-10-12T12:29:00+03:00] Slave db.stefbdb3.st.skroutz.gr [2] has been elected as a new master  cluster=stefbtest
INFO[2017-10-12T12:29:00+03:00] Terminating all threads on db.stefbdb.st.skroutz.gr  cluster=stefbtest
INFO[2017-10-12T12:29:00+03:00] Rejecting updates on db.stefbdb.st.skroutz.gr (old master)  cluster=stefbtest
INFO[2017-10-12T12:29:00+03:00] Waiting for candidate Master to synchronize   cluster=stefbtest
INFO[2017-10-12T12:29:00+03:00] Stopping slave thread on new master           cluster=stefbtest
INFO[2017-10-12T12:29:00+03:00] Calling post-failover script                  cluster=stefbtest
INFO[2017-10-12T12:29:01+03:00] Post-failover script complete%!(EXTRA string=sysctl: cannot stat /proc/sys/net/ipv6/conf/eth0:db/accept_ra: No such file or directory
sysctl: cannot stat /proc/sys/net/ipv6/conf/eth0:db/autoconf: No such file or directory
Removing the shared ip from db.stefbdb.st.skroutz.gr
Success
Adding the shared ip to db.stefbdb3.st.skroutz.gr
Success
)  cluster=stefbtest
INFO[2017-10-12T12:29:01+03:00] Resetting slave on new master and set read/write mode on  cluster=stefbtest
INFO[2017-10-12T12:29:01+03:00] Inject fake transaction on new master db.stefbdb3.st.skroutz.gr   cluster=stefbtest
INFO[2017-10-12T12:29:01+03:00] Switching old master as a slave               cluster=stefbtest
INFO[2017-10-12T12:29:01+03:00] Doing GTID switch                             cluster=stefbtest
INFO[2017-10-12T12:29:01+03:00] Switching other slaves to the new master      cluster=stefbtest
INFO[2017-10-12T12:29:01+03:00] Waiting for slave db.stefbdb1.st.skroutz.gr to sync  cluster=stefbtest
INFO[2017-10-12T12:29:01+03:00] Change master on slave db.stefbdb1.st.skroutz.gr  cluster=stefbtest
INFO[2017-10-12T12:29:01+03:00] Waiting for slave db.stefbdb2.st.skroutz.gr to sync  cluster=stefbtest
INFO[2017-10-12T12:29:01+03:00] Change master on slave db.stefbdb2.st.skroutz.gr  cluster=stefbtest
INFO[2017-10-12T12:29:01+03:00] Waiting for slave db.stefbdb4.st.skroutz.gr to sync  cluster=stefbtest
INFO[2017-10-12T12:29:01+03:00] Change master on slave db.stefbdb4.st.skroutz.gr  cluster=stefbtest
INFO[2017-10-12T12:29:01+03:00] Master switch on db.stefbdb3.st.skroutz.gr complete  cluster=stefbtest
# replication-manager --config-group stefbtest topology
INFO[2017-10-12T12:29:05+03:00] Server [0] db.stefbdb.st.skroutz.gr Slave     cluster=stefbtest
INFO[2017-10-12T12:29:05+03:00] Server [1] db.stefbdb1.st.skroutz.gr Slave    cluster=stefbtest
INFO[2017-10-12T12:29:05+03:00] Server [2] db.stefbdb2.st.skroutz.gr Slave    cluster=stefbtest
INFO[2017-10-12T12:29:05+03:00] Server [3] db.stefbdb3.st.skroutz.gr Master   cluster=stefbtest
INFO[2017-10-12T12:29:05+03:00] Server [4] db.stefbdb4.st.skroutz.gr Slave    cluster=stefbtest
# replication-manager --config-group stefbtest failover
INFO[2017-10-12T12:29:07+03:00] [stefbtest] WARN : Could not read values from state file:EOF 
ERRO[2017-10-12T12:29:07+03:00] Could not open connection to server valid1.skroutz.gr : ERROR: DNS resolution error for host valid1.skroutz.gr  cluster=stefbtest
ERRO[2017-10-12T12:29:07+03:00] Could not open connection to server valid2.skroutz.gr : ERROR: DNS resolution error for host valid2.skroutz.gr  cluster=stefbtest
INFO[2017-10-12T12:29:07+03:00] Loading 0 proxies                             cluster=stefbtest
INFO[2017-10-12T12:29:07+03:00] [stefbtest] ERR00010 Could not find a slave in topology 
INFO[2017-10-12T12:29:07+03:00] [stefbtest] ERR00012 Could not find a master in topology 
ERRO[2017-10-12T12:29:07+03:00] Could not find a failed server in the hosts list  cluster=stefbtest
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0xa1478a]

goroutine 1 [running]:
github.com/signal18/replication-manager/cluster.(*Cluster).Close(0xc42006f800)
	/var/jenkins_home/workspace/go/src/github.com/signal18/replication-manager/cluster/cluster.go:616 +0x4a
main.glob..func10(0x137a6c0, 0xc4202afe80, 0x0, 0x2)
	/var/jenkins_home/workspace/go/src/github.com/signal18/replication-manager/repmgr.go:236 +0x2d
github.com/signal18/replication-manager/vendor/github.com/spf13/cobra.(*Command).execute(0x137a6c0, 0xc4202afce0, 0x2, 0x2, 0x137a6c0, 0xc4202afce0)
	/var/jenkins_home/workspace/go/src/github.com/signal18/replication-manager/vendor/github.com/spf13/cobra/command.go:655 +0x35b
github.com/signal18/replication-manager/vendor/github.com/spf13/cobra.(*Command).ExecuteC(0x1379a00, 0x11, 0x1, 0x0)
	/var/jenkins_home/workspace/go/src/github.com/signal18/replication-manager/vendor/github.com/spf13/cobra/command.go:734 +0x339
github.com/signal18/replication-manager/vendor/github.com/spf13/cobra.(*Command).Execute(0x1379a00, 0x0, 0x0)
	/var/jenkins_home/workspace/go/src/github.com/signal18/replication-manager/vendor/github.com/spf13/cobra/command.go:693 +0x2b
main.main()
	/var/jenkins_home/workspace/go/src/github.com/signal18/replication-manager/main.go:166 +0x31
```

What it should do is this
(after I left only the [Default] config-group. Though the actual name does not seem to make a diffrence)
```
# replication-manager failover
INFO[2017-10-12T12:23:22+03:00] Loading 0 proxies                             cluster=Default
INFO[2017-10-12T12:23:22+03:00] [Default] INFO : Starting master switch      
INFO[2017-10-12T12:23:22+03:00] Electing a new master                         cluster=Default
INFO[2017-10-12T12:23:22+03:00] Slave db.stefbdb.st.skroutz.gr [0] has been elected as a new master  cluster=Default
INFO[2017-10-12T12:23:22+03:00] Waiting for candidate master to apply relay log  cluster=Default
INFO[2017-10-12T12:23:22+03:00] Reading all relay logs on db.stefbdb.st.skroutz.gr  cluster=Default
INFO[2017-10-12T12:23:22+03:00] Save replication status before electing      
INFO[2017-10-12T12:23:22+03:00] master_log_file=mysql-bin.000002              cluster=Default
INFO[2017-10-12T12:23:22+03:00] master_log_pos=3308                           cluster=Default
INFO[2017-10-12T12:23:22+03:00] Candidate was in sync=true                    cluster=Default
INFO[2017-10-12T12:23:22+03:00] Stopping slave thread on new master           cluster=Default
INFO[2017-10-12T12:23:22+03:00] Calling post-failover script                  cluster=Default
INFO[2017-10-12T12:23:23+03:00] Post-failover script complete%!(EXTRA string=sysctl: cannot stat /proc/sys/net/ipv6/conf/eth0:db/accept_ra: No such file or directory
sysctl: cannot stat /proc/sys/net/ipv6/conf/eth0:db/autoconf: No such file or directory
Removing the shared ip from db.stefbdb3.st.skroutz.gr
Success
Adding the shared ip to db.stefbdb.st.skroutz.gr
Success
)  cluster=Default
INFO[2017-10-12T12:23:23+03:00] Resetting slave on new master and set read/write mode on  cluster=Default
INFO[2017-10-12T12:23:23+03:00] Inject fake transaction on new master db.stefbdb.st.skroutz.gr   cluster=Default
INFO[2017-10-12T12:23:25+03:00] Switching other slaves to the new master      cluster=Default
INFO[2017-10-12T12:23:25+03:00] Change master on slave db.stefbdb4.st.skroutz.gr  cluster=Default
INFO[2017-10-12T12:23:25+03:00] Change master on slave db.stefbdb1.st.skroutz.gr  cluster=Default
INFO[2017-10-12T12:23:25+03:00] Change master on slave db.stefbdb2.st.skroutz.gr  cluster=Default
INFO[2017-10-12T12:23:25+03:00] Master switch on db.stefbdb.st.skroutz.gr complete  cluster=Default
# replication-manager topology
INFO[2017-10-12T12:23:29+03:00] Server [0] db.stefbdb.st.skroutz.gr Master    cluster=Default
INFO[2017-10-12T12:23:29+03:00] Server [1] db.stefbdb1.st.skroutz.gr Slave    cluster=Default
INFO[2017-10-12T12:23:29+03:00] Server [2] db.stefbdb2.st.skroutz.gr Slave    cluster=Default
INFO[2017-10-12T12:23:29+03:00] Server [3] db.stefbdb3.st.skroutz.gr StandAlone   cluster=Default
INFO[2017-10-12T12:23:29+03:00] Server [4] db.stefbdb4.st.skroutz.gr Slave    cluster=Default
# 
```

Are you planning to drop support for the cli? We use our own tools (nagios) to monitor the health of the MySQL cluster and the cli interface is convenient (in a way).

**Comment by tanji** [comment]
We are not planning to drop support for the CLI, simply said, it's not as well tested as the monitor is.
In 2.0 the CLI is revamped and using the API. You might want to test the last version (check in http://ci.signal18.io/mrm/builds/develop) however most of the options have been renamed for consistency. All of this is now documented in https://docs.signal18.io for clarity.
If the domain names don't resolve properly indeed, it can cause unforeseen issues. I haven't tested it with two sections yet, but I will try to check and reproduce what could have happened, we've had a similar issue in 2.0 recently, so maybe it's an easy fix.

**Comment by svaroqui** [comment]
Yes i would suggest 2.0 for any client interaction  , please use the osc release it comes with osc and cli , in 2.0 the monitor is always up in daemon mode and client are using JWT API to query the daemon it's a much correct architecture , the cli can be installed on same or different servers and the server can retain states of each cluster instead of re discovering all time , if it can be rediscover at all , some states are lost when using old cli solution without the monitoring

**Comment by vfxcode** [comment]
Yes I have tested the 2.0 version, and I agree with the architecture, but I am a bit skeptical about using the development branch in production just yet.
The monitor interface is fine and it should work (for us), however I was expecting it to behave identically to the cli interface so I did my pre-production tests through that.
The failover issue I reported in my previous comment is a bit dangerous since it might cripple a different replication-setup without any warning. You can see that is config-group is the same as the topology/switchover however the failover command tries to connect to two hosts not the config-group. Again it seems to work fine through monitor.

**Comment by svaroqui** [comment]
Tx, FYI, 2.0 will be the first release with automated quality checks http://ci.signal18.io/results/ and the first one we will offer support suscription  via signal18

**Comment by vfxcode** [comment]
Excellent!

**Comment by svaroqui** [comment]
Hello again, 
Guessing 2.0-rc fixed this issue ? 

We started working on 2.1 with streaming backups and dynamic config (adding cluster on the fly and saving config changes )  in 2.0  there is already an include directory that can be specify where you can splt each cluster conf , for 2.1 such same stuff is hardcoded into $datadir/cluster.d/ 

Rds
Svar

**Comment by vfxcode** [comment]
I have not tested this yet.
I will and I will come back with results but for now I think we can close this and report a new one if there are any more issues like this.

**Comment by svaroqui** [comment]
Thanks for keeping us in the loop
