### ISSUE TITLE
GTID rejoin failed using MySQL 

### ISSUE THREAD

**Issue by boris-ragulin** [signal18/replication-manager#193]
Hi,

I'm trying to setup the master-slave cluster of 3 servers using MySQL 5.7 and replication-manager on Ubuntu 16.04. But eventually the topology is detected wrong as `multi-tier-slave` despite the configuration option `multi-tier-slave = false`. It's leading to the fact that master is detected as relay and failover/switchover are not working.

```
root@test-mysql57-0:~# mysql -V
mysql  Ver 14.14 Distrib 5.7.20, for Linux (x86_64) using  EditLine wrapper
```

```
root@test-mysql57-0:~# replication-manager version
Replication Manager 1.1.3 for MariaDB 10.x and MySQL 5.7 Series
Full Version:  1.1.3-1-g8385dea9
Build Time:  2017-11-15T18:30:09+0000
```

[config.toml.zip](https://github.com/signal18/replication-manager/files/1567893/config.toml.zip)

```
2017/12/18 12:34:30 [cluster_test] INFO  - New server monitored: 10.132.0.5:3306
2017/12/18 12:34:30 [cluster_test] INFO  - New server monitored: 10.132.0.6:3306
2017/12/18 12:34:30 [cluster_test] INFO  - New server monitored: 10.132.0.7:3306
2017/12/18 12:34:30 [cluster_test] INFO  - Loading 0 proxies
2017/12/18 12:34:30 [cluster_test] INFO  - Failover in interactive mode
2017/12/18 12:34:31 [cluster_test] DEBUG - Lookup server 10.132.0.5:3306 if maxscale binlog server: 10.132.0.6:3306
2017/12/18 12:34:31 [cluster_test] DEBUG - Lookup server 10.132.0.6:3306 if maxscale binlog server: 10.132.0.6:3306
2017/12/18 12:34:31 [cluster_test] DEBUG - Lookup server 10.132.0.7:3306 if maxscale binlog server: 10.132.0.6:3306
2017/12/18 12:34:32 [cluster_test] DEBUG - Lookup server 10.132.0.5:3306 if maxscale binlog server: 10.132.0.6:3306
2017/12/18 12:34:32 [cluster_test] DEBUG - Lookup server 10.132.0.6:3306 if maxscale binlog server: 10.132.0.6:3306
2017/12/18 12:34:32 [cluster_test] DEBUG - Lookup server 10.132.0.7:3306 if maxscale binlog server: 10.132.0.6:3306
2017/12/18 12:34:32 [cluster_test] DEBUG - Monitoring server loop
2017/12/18 12:34:32 [cluster_test] DEBUG - Server [0]: URL: 10.132.0.5:3306 State:        PrevState:       
2017/12/18 12:34:32 [cluster_test] DEBUG - Server [1]: URL: 10.132.0.6:3306 State:        PrevState:       
2017/12/18 12:34:32 [cluster_test] DEBUG - Server [2]: URL: 10.132.0.7:3306 State:        PrevState:       
2017/12/18 12:34:32 [cluster_test] DEBUG - State unconnected set by non-master rule on server 10.132.0.6:3306
2017/12/18 12:34:32 [cluster_test] DEBUG - Entering topology detection
2017/12/18 12:34:32 [cluster_test] DEBUG - Server 10.132.0.5:3306 is configured as a slave
2017/12/18 12:34:32 [cluster_test] DEBUG - Privilege check on 10.132.0.5:3306
2017/12/18 12:34:32 [cluster_test] DEBUG - Client connection found on server 10.132.0.5:3306 with IP 10.132.0.6 for host 10.132.0.6
2017/12/18 12:34:32 [cluster_test] DEBUG - Server 10.132.0.6:3306 is configured as a slave
2017/12/18 12:34:32 [cluster_test] DEBUG - Privilege check on 10.132.0.6:3306
2017/12/18 12:34:32 [cluster_test] DEBUG - Client connection found on server 10.132.0.6:3306 with IP 10.132.0.6 for host test-mysql57-0.c.eastern-monitor-162515.internal
2017/12/18 12:34:33 [cluster_test] DEBUG - Server 10.132.0.7:3306 is configured as a slave
2017/12/18 12:34:33 [cluster_test] DEBUG - Privilege check on 10.132.0.7:3306
2017/12/18 12:34:33 [cluster_test] DEBUG - Client connection found on server 10.132.0.7:3306 with IP 10.132.0.6 for host test-mysql57-0.c.eastern-monitor-162515.internal
2017/12/18 12:34:33 [cluster_test] DEBUG - Rejoin replication master id 1 was lookup if master admin:admin@tcp(10.132.0.5:3306)/?timeout=5s&readTimeout=15s is that one : 2
2017/12/18 12:34:33 [cluster_test] DEBUG - Rejoin replication master id 1 was lookup if master admin:admin@tcp(10.132.0.6:3306)/?timeout=5s&readTimeout=15s is that one : 1
2017/12/18 12:34:33 [cluster_test] DEBUG - Rejoin replication master id 0 was lookup if master admin:admin@tcp(10.132.0.5:3306)/?timeout=5s&readTimeout=15s is that one : 2
2017/12/18 12:34:33 [cluster_test] DEBUG - Rejoin replication master id 0 was lookup if master admin:admin@tcp(10.132.0.6:3306)/?timeout=5s&readTimeout=15s is that one : 1
2017/12/18 12:34:33 [cluster_test] DEBUG - Rejoin replication master id 0 was lookup if master admin:admin@tcp(10.132.0.7:3306)/?timeout=5s&readTimeout=15s is that one : 3
2017/12/18 12:34:33 [cluster_test] DEBUG - Rejoin replication master id 0 was lookup if master admin:admin@tcp(10.132.0.5:3306)/?timeout=5s&readTimeout=15s is that one : 2
2017/12/18 12:34:33 [cluster_test] DEBUG - Rejoin replication master id 0 was lookup if master admin:admin@tcp(10.132.0.6:3306)/?timeout=5s&readTimeout=15s is that one : 1
2017/12/18 12:34:33 [cluster_test] DEBUG - Rejoin replication master id 0 was lookup if master admin:admin@tcp(10.132.0.7:3306)/?timeout=5s&readTimeout=15s is that one : 3
2017/12/18 12:34:33 [cluster_test] DEBUG - Rejoin replication master id 1 was lookup if master admin:admin@tcp(10.132.0.5:3306)/?timeout=5s&readTimeout=15s is that one : 2
2017/12/18 12:34:33 [cluster_test] DEBUG - Rejoin replication master id 1 was lookup if master admin:admin@tcp(10.132.0.6:3306)/?timeout=5s&readTimeout=15s is that one : 1
2017/12/18 12:34:33 [cluster_test] DEBUG - Rejoin replication master id 0 was lookup if master admin:admin@tcp(10.132.0.5:3306)/?timeout=5s&readTimeout=15s is that one : 2
2017/12/18 12:34:33 [cluster_test] DEBUG - Rejoin replication master id 0 was lookup if master admin:admin@tcp(10.132.0.6:3306)/?timeout=5s&readTimeout=15s is that one : 1
2017/12/18 12:34:33 [cluster_test] DEBUG - Rejoin replication master id 0 was lookup if master admin:admin@tcp(10.132.0.7:3306)/?timeout=5s&readTimeout=15s is that one : 3
2017/12/18 12:34:33 [cluster_test] WARN  - Undiscovered master, skipping failover check
2017/12/18 12:34:33 [cluster_test] STATE - ERR00012 Could not find a master in topology
```

And show slave status on the master (test-mysql57-0 / 10.132.0.6):
```
mysql> show slave status \G;
Empty set (0.00 sec)

ERROR: 
No query specified

mysql> 
```

Could you please advise how to debug that or what I'm doing wrong?

Thank you.

**Comment by svaroqui** [comment]
Hello phewphew, 

MySQL non GTID replication is only supported in 2.0 branch , 
You can found -osc (open source branch) in our depot or via direct download here http://ci.signal18.io/mrm/builds/develop/

Also 2.0 as support for pseudo-gtid that i would advise you to use in non GTID replication mode   
Tx 
Stéphane

**Comment by svaroqui** [comment]
Re,

Also thinking of the branch you are using branch there is an other possibilty is that the master have a non working replication pending, to check this just go the master show slave status and issue reset slave if the slave status report something ! 

/svar

**Comment by boris-ragulin** [comment]
Thank you, I will try 2.0.

BTW, GTID is ON:

```
mysql> select @@global.gtid_mode;
+--------------------+
| @@global.gtid_mode |
+--------------------+
| ON                 |
+--------------------+
1 row in set (0.00 sec)
```

And I performed reset slave all.

**Comment by svaroqui** [comment]
Ok i'm sure 2.0 is working as we have test case inside it , please let us know how it goes !

**Comment by boris-ragulin** [comment]
Yeap, it seems that it's working right now - topology detection, switchover, failover are ok.
But catched panic on failed node joining back to the cluster.

```
INFO[2017-12-18T13:34:00Z] Setting Read Only on rejoined 10.132.0.6:3306  cluster=cluster_haproxy_masterslave
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0xadd8e6]

goroutine 24159 [running]:
github.com/signal18/replication-manager/cluster.(*ServerMonitor).rejoinMasterSync(0xc420112900, 0xc4204b98f0, 0x0, 0xd98a5b)
        /var/jenkins_home/workspace/go/src/github.com/signal18/replication-manager/cluster/srv_rejoin.go:122 +0xf6
github.com/signal18/replication-manager/cluster.(*ServerMonitor).rejoinMasterIncremental(0xc420112900, 0xc4204b98f0, 0x0, 0x0)
        /var/jenkins_home/workspace/go/src/github.com/signal18/replication-manager/cluster/srv_rejoin.go:274 +0x1fe
github.com/signal18/replication-manager/cluster.(*ServerMonitor).RejoinMaster(0xc420112900, 0x1202ba0, 0xc420537940)
        /var/jenkins_home/workspace/go/src/github.com/signal18/replication-manager/cluster/srv_rejoin.go:59 +0x2c2
github.com/signal18/replication-manager/cluster.(*ServerMonitor).Ping(0xc420112900, 0xc420331db0)
        /var/jenkins_home/workspace/go/src/github.com/signal18/replication-manager/cluster/srv.go:300 +0x155d
created by github.com/signal18/replication-manager/cluster.(*Cluster).TopologyDiscover
        /var/jenkins_home/workspace/go/src/github.com/signal18/replication-manager/cluster/topology.go:108 +0xce
```

**Comment by svaroqui** [comment]
ok that's line : server.CurrentGtid.Sprint(), crash.FailoverIOGtid.Sprint())  , any thing suspicious in the logs about crash information can't be saved ?

**Comment by svaroqui** [comment]
Looks like rejoin code for MariaDB only :(

**Comment by svaroqui** [comment]
Can you check last build, i pushed some code change that process MySQL GTID as if they are Like MariaDB GTID on domain 0  and hashing server UUID to uint64, you can share http /servers and /crashes information before rejoin would help our testing framework currently in used for a client !

**Comment by boris-ragulin** [comment]
Hi,

It throws another error:

```
root@test-mysql57-0:/etc/replication-manager# replication-manager-osc --config=config.toml monitor
INFO[2017-12-19T08:17:04Z] replication-manager started in daemon mode    version=2.0.0-dev
INFO[2017-12-19T08:17:04Z] No existing password encryption scheme        error="Key file does not exist"
INFO[2017-12-19T08:17:04Z] Loading database TLS certificates             cluster=cluster_haproxy_masterslave
INFO[2017-12-19T08:17:04Z] Don't Have database TLS certificates          cluster=cluster_haproxy_masterslave
INFO[2017-12-19T08:17:04Z] New server monitored: 10.132.0.5:3306         cluster=cluster_haproxy_masterslave
INFO[2017-12-19T08:17:04Z] New server monitored: 10.132.0.6:3306         cluster=cluster_haproxy_masterslave
INFO[2017-12-19T08:17:04Z] New server monitored: 10.132.0.7:3306         cluster=cluster_haproxy_masterslave
INFO[2017-12-19T08:17:04Z] Failover in interactive mode                  cluster=cluster_haproxy_masterslave
INFO[2017-12-19T08:17:04Z] Loading 0 proxies                             cluster=cluster_haproxy_masterslave
WARN[2017-12-19T08:17:04Z] File error: open /var/lib/replication-manager/cluster_haproxy_masterslave/clusterstate.json: no such file or directory
  cluster=cluster_haproxy_masterslave
INFO[2017-12-19T08:17:05Z] Starting http monitor on port 10001          
panic: runtime error: index out of range

goroutine 22 [running]:
github.com/signal18/replication-manager/gtid.NewMySQLGtid(0xc4203e4600, 0x28, 0xd78ce2)
        /var/jenkins_home/workspace/go/src/github.com/signal18/replication-manager/gtid/gtid.go:133 +0x1d3
github.com/signal18/replication-manager/gtid.NewMySQLList(0xc4203e4600, 0x52, 0xd8302a)
        /var/jenkins_home/workspace/go/src/github.com/signal18/replication-manager/gtid/gtid.go:110 +0xbe
github.com/signal18/replication-manager/cluster.(*ServerMonitor).Refresh(0xc42010a900, 0x0, 0x0)
        /var/jenkins_home/workspace/go/src/github.com/signal18/replication-manager/cluster/srv.go:443 +0x19d0
github.com/signal18/replication-manager/cluster.(*ServerMonitor).Ping(0xc42010a900, 0xc4202e1d90)
        /var/jenkins_home/workspace/go/src/github.com/signal18/replication-manager/cluster/srv.go:278 +0xdcf
created by github.com/signal18/replication-manager/cluster.(*Cluster).TopologyDiscover
        /var/jenkins_home/workspace/go/src/github.com/signal18/replication-manager/cluster/topology.go:108 +0xce
```

Cluster is configured as follows:

```
[Cluster_Haproxy_MasterSlave]
title = "ClusterTestMasterSlave"

db-servers-hosts = "10.132.0.5:3306,10.132.0.6:3306,10.132.0.7:3306"
db-servers-prefered-master = "10.132.0.6:3306"
db-servers-credential = "admin:admin"
db-servers-connect-timeout = 1

replication-credential = "slave:slave"
replication-multi-master = false
replication-multi-tier-slave = false

haproxy = false
haproxy-write-port = 3303
haproxy-read-port = 3302
```

**Comment by svaroqui** [comment]
Hi , thanks for your help! I can reproduce it now, will work for a fixe !

**Comment by svaroqui** [comment]
Re,

Ok you should be good to go now with last code: 
Tested ut here http://repmgr-2.signal18.io/
Thanks again for the help here , 

Closint bug  for now Reopen if needed 

Did you notice we do monitoring as well via Grafana !

**Comment by boris-ragulin** [comment]
Thank you! I'll check it a bit later.
