### ISSUE TITLE
Nil pointer dereference on /api/clusters/<name>/status

### ISSUE THREAD

**Issue by ylacancellera** [signal18/replication-manager#357]
Hi

I'm stuck with a panic when calling this route, is it this field https://github.com/signal18/replication-manager/blob/2.1/cluster/cluster.go#L106 ?

### Version

2.1.5

### Step to reproduce

`TOKEN=$(curl -s -k -X POST -H 'Accept: application/json' -H 'Content-Type: application/json' --data '{"username":"admin","password":"repman"}' https://<hostname>:10005/api/login -v )`

`curl -k --header 'Accept: application/json' --header "Authorization: Bearer ${TOKEN}" https://<hostname>:10005/api/clusters/<name>/status -v`

### Error logs

```
Jun 30 17:42:47 hostname replication-manager-osc[1547363]: 2021/06/30 17:42:47 http2: panic serving 10.0.16.3:59990: runtime error: invalid memory address or nil pointer dereference
Jun 30 17:42:47 hostname replication-manager-osc[1547363]: goroutine 153737 [running]:
Jun 30 17:42:47 hostname replication-manager-osc[1547363]: net/http.(*http2serverConn).runHandler.func1(0xc000010e08, 0xc0001c5f8e, 0xc000c38600)
Jun 30 17:42:47 hostname replication-manager-osc[1547363]: #011/var/jenkins_home/tools/org.jenkinsci.plugins.golang.GolangInstallation/Go_1.16/src/net/http/h2_bundle.go:5716 +0x193
Jun 30 17:42:47 hostname replication-manager-osc[1547363]: panic(0x1dd3e20, 0x3070bf0)
Jun 30 17:42:47 hostname replication-manager-osc[1547363]: #011/var/jenkins_home/tools/org.jenkinsci.plugins.golang.GolangInstallation/Go_1.16/src/runtime/panic.go:965 +0x1b9
Jun 30 17:42:47 hostname replication-manager-osc[1547363]: github.com/signal18/replication-manager/cluster.(*Cluster).GetStatus(...)
Jun 30 17:42:47 hostname replication-manager-osc[1547363]: #011/var/jenkins_home/workspace/go/src/github.com/signal18/replication-manager/cluster/cluster_get.go:241
Jun 30 17:42:47 hostname replication-manager-osc[1547363]: github.com/signal18/replication-manager/server.(*ReplicationManager).handlerMuxClusterStatus(0xc00049e000, 0x7f67337d0ce0, 0xc000010e18, 0xc000c47000)
Jun 30 17:42:47 hostname replication-manager-osc[1547363]: #011/var/jenkins_home/workspace/go/src/github.com/signal18/replication-manager/server/api_cluster.go:1465 +0x262 
Jun 30 17:42:47 hostname replication-manager-osc[1547363]: net/http.HandlerFunc.ServeHTTP(0xc00020a0d0, 0x7f67337d0ce0, 0xc000010e18, 0xc000c47000)
Jun 30 17:42:47 hostname replication-manager-osc[1547363]: #011/var/jenkins_home/tools/org.jenkinsci.plugins.golang.GolangInstallation/Go_1.16/src/net/http/server.go:2069 +0x44
Jun 30 17:42:47 hostname replication-manager-osc[1547363]: github.com/codegangsta/negroni.Wrap.func1(0x7f67337d0ce0, 0xc000010e18, 0xc000c47000, 0xc000d282e0)
Jun 30 17:42:47 hostname replication-manager-osc[1547363]: #011/var/jenkins_home/workspace/go/pkg/mod/github.com/codegangsta/negroni@v0.3.0/negroni.go:46 +0x4d
Jun 30 17:42:47 hostname replication-manager-osc[1547363]: github.com/codegangsta/negroni.HandlerFunc.ServeHTTP(0xc0005b82d0, 0x7f67337d0ce0, 0xc000010e18, 0xc000c47000, 0xc000d282e0)
Jun 30 17:42:47 hostname replication-manager-osc[1547363]: #011/var/jenkins_home/workspace/go/pkg/mod/github.com/codegangsta/negroni@v0.3.0/negroni.go:29 +0x4e
Jun 30 17:42:47 hostname replication-manager-osc[1547363]: github.com/codegangsta/negroni.middleware.ServeHTTP(0x2382e40, 0xc0005b82d0, 0xc0005b82e8, 0x7f67337d0ce0, 0xc000010e18, 0xc000c47000)
Jun 30 17:42:47 hostname replication-manager-osc[1547363]: #011/var/jenkins_home/workspace/go/pkg/mod/github.com/codegangsta/negroni@v0.3.0/negroni.go:38 +0x9c
Jun 30 17:42:47 hostname replication-manager-osc[1547363]: github.com/codegangsta/negroni.(*Negroni).ServeHTTP(0xc000610ba0, 0x23b6ce8, 0xc000010e08, 0xc000c47000)
Jun 30 17:42:47 hostname replication-manager-osc[1547363]: #011/var/jenkins_home/workspace/go/pkg/mod/github.com/codegangsta/negroni@v0.3.0/negroni.go:96 +0xf1
Jun 30 17:42:47 hostname replication-manager-osc[1547363]: github.com/gorilla/mux.(*Router).ServeHTTP(0xc0000f6070, 0x23b6ce8, 0xc000010e08, 0xc000c46d00)
Jun 30 17:42:47 hostname replication-manager-osc[1547363]: #011/var/jenkins_home/workspace/go/pkg/mod/github.com/gorilla/mux@v0.0.0-20180120075819-c0091a029979/mux.go:159 +0x106 
Jun 30 17:42:47 hostname replication-manager-osc[1547363]: github.com/gorilla/handlers.(*cors).ServeHTTP(0xc0004783f0, 0x23b6ce8, 0xc000010e08, 0xc000c46d00)
Jun 30 17:42:47 hostname replication-manager-osc[1547363]: #011/var/jenkins_home/workspace/go/pkg/mod/github.com/gorilla/handlers@v1.3.0/cors.go:51 +0xff4 
Jun 30 17:42:47 hostname replication-manager-osc[1547363]: net/http.serverHandler.ServeHTTP(0xc0007a8000, 0x23b6ce8, 0xc000010e08, 0xc000c46d00)
Jun 30 17:42:47 hostname replication-manager-osc[1547363]: #011/var/jenkins_home/tools/org.jenkinsci.plugins.golang.GolangInstallation/Go_1.16/src/net/http/server.go:2887 +0xa3
Jun 30 17:42:47 hostname replication-manager-osc[1547363]: net/http.initALPNRequest.ServeHTTP(0x23be708, 0xc000ca8120, 0xc000aa3500, 0xc0007a8000, 0x23b6ce8, 0xc000010e08, 0xc000c46d00)
Jun 30 17:42:47 hostname replication-manager-osc[1547363]: #011/var/jenkins_home/tools/org.jenkinsci.plugins.golang.GolangInstallation/Go_1.16/src/net/http/server.go:3459 +0x8d
Jun 30 17:42:47 hostname replication-manager-osc[1547363]: net/http.(*http2serverConn).runHandler(0xc000c38600, 0xc000010e08, 0xc000c46d00, 0xc000d1c948)
Jun 30 17:42:47 hostname replication-manager-osc[1547363]: #011/var/jenkins_home/tools/org.jenkinsci.plugins.golang.GolangInstallation/Go_1.16/src/net/http/h2_bundle.go:5723 +0x8b
Jun 30 17:42:47 hostname replication-manager-osc[1547363]: created by net/http.(*http2serverConn).processHeaders
Jun 30 17:42:47 hostname replication-manager-osc[1547363]: #011/var/jenkins_home/tools/org.jenkinsci.plugins.golang.GolangInstallation/Go_1.16/src/net/http/h2_bundle.go:5453 +0x505 
```

**Comment by svaroqui** [comment]
Hi thanks for reporting this bug .

I can quickly fixe this, that's because i don't test if result of getCluster return a valid object  "name" is not a valid cluster in you configuration ? 
I can send  back an http error for the 2.1 but we are currently on new release working on a  V3 OpenApi that would work using  grpc or json and it's already fixing that issue may you should base your work on 2.2 if i start merging grpc-api into it   
https://github.com/terwey/replication-manager/tree/grpc_api

**Comment by ylacancellera** [comment]
Thanks, I did not notice I sent a non existing cluster name...

Could your version allow to bypass jwt tokens ?
We are having trouble with a monitoring stack because of this, I was just thinking of doing a PR

**Comment by svaroqui** [comment]
Yes if you don't disable http on port 10001,  
```
curl http://127.0.0.1:10001/api/clusters/cluster_test_masterslaveslave/status 
{"alive": "running"}
```

**Comment by svaroqui** [comment]
Yes this is unprotected  
```
curl -k https://127.0.0.1:10005/api/clusters/cluster_test_masterslaveslave/status
{"alive": "running"}
```

**Comment by ylacancellera** [comment]
Yes but /api/monitor is not, and we would prefer it unprotected (not by default ofc)

**Comment by svaroqui** [comment]
/api/monitor are a collection of configuration stuff  not exposing any password but it can possibly be protected by default , is this what you would like ?

**Comment by ylacancellera** [comment]
I switched between too many versions, I got confused I guess, this is in fact unprotected in last version just as I need
Sorry for the noise...

**Comment by svaroqui** [comment]
Ok the fix for the nil pointer will be in next release 2.1.6 feel free to reopen if needed
