### ISSUE TITLE
crash when setup replication-manager

### ISSUE THREAD

**Issue by bmillemathias** [signal18/replication-manager#359]
version: `2.1.6.`

I was trying to setup replication-manager and understanding a strange behavior (the dedicated root alike user was not using the password I gave it in the filed `db-servers-credential` and constantly connecting to the mysql node without password according my mysql error log) when I decided to remove the password to at least see if replication-manager is able to connect with an empty password.
on my 3 nodes replication setup, I removed the password of the `repl-manager` user on one of the slave (but not on the master and the other slave) and suddenly replication-manager was able to connect to this node but crash right after

```
Jul 07 14:25:18 bmm-4 systemd[1]: Started replication-manager open source.
Jul 07 14:25:19 bmm-4 replication-manager-osc[5300]: time="2021-07-07T14:25:19Z" level=warning msg="No include directory in default section"
Jul 07 14:25:19 bmm-4 replication-manager-osc[5300]: time="2021-07-07T14:25:19Z" level=warning msg="No monitoring-save-config variable in default section config change lost on restart"
Jul 07 14:25:19 bmm-4 replication-manager-osc[5300]: time="2021-07-07T14:25:19Z" level=info msg="Replication-Manager started in daemon mode" version=v2.1.6
Jul 07 14:25:19 bmm-4 replication-manager-osc[5300]: time="2021-07-07T14:25:19Z" level=info msg="Failover in interactive mode" cluster=Default
Jul 07 14:25:19 bmm-4 replication-manager-osc[5300]: 2021/07/07 14:25:19 ERROR: ciphertext too short
Jul 07 14:25:19 bmm-4 replication-manager-osc[5300]: 2021/07/07 14:25:19 ERROR: ciphertext too short
Jul 07 14:25:19 bmm-4 replication-manager-osc[5300]: 2021/07/07 14:25:19 ERROR: ciphertext too short
Jul 07 14:25:20 bmm-4 replication-manager-osc[5300]: time="2021-07-07T14:25:20Z" level=info msg="Starting HTTPS & JWT API on 0.0.0.0:10005"
Jul 07 14:25:24 bmm-4 replication-manager-osc[5300]: time="2021-07-07T14:25:24Z" level=info msg="No database TLS certificates" cluster=Default
Jul 07 14:25:24 bmm-4 replication-manager-osc[5300]: time="2021-07-07T14:25:24Z" level=info msg="No database previous TLS certificates" cluster=Default
Jul 07 14:25:24 bmm-4 replication-manager-osc[5300]: 2021/07/07 14:25:24 ERROR: ciphertext too short
Jul 07 14:25:24 bmm-4 replication-manager-osc[5300]: 2021/07/07 14:25:24 ERROR: ciphertext too short
Jul 07 14:25:24 bmm-4 replication-manager-osc[5300]: time="2021-07-07T14:25:24Z" level=info msg="Loading 0 proxies" cluster=Default
Jul 07 14:25:24 bmm-4 replication-manager-osc[5300]: time="2021-07-07T14:25:24Z" level=info msg="Loading database configurator config /usr/share/replication-manager/opensvc/moduleset_mariadb.svc.mrm.db.json" cluster=Default
Jul 07 14:25:24 bmm-4 replication-manager-osc[5300]: time="2021-07-07T14:25:24Z" level=info msg="Loading proxies configurator config /usr/share/replication-manager/opensvc/moduleset_mariadb.svc.mrm.proxy.json" cluster=Default
Jul 07 14:25:24 bmm-4 replication-manager-osc[5300]: time="2021-07-07T14:25:24Z" level=info msg="Assigning a global connection on server bmm-3:3306" cluster=Default
Jul 07 14:25:26 bmm-4 replication-manager-osc[5300]: time="2021-07-07T14:25:26Z" level=info msg="Assuming failed server bmm-1:3306 was a master" cluster=Default
Jul 07 14:25:26 bmm-4 replication-manager-osc[5300]: time="2021-07-07T14:25:26Z" level=warning msg="Could not find a slave in topology" cluster=Default code=ERR00010 status=RESOLV type=state
Jul 07 14:25:26 bmm-4 replication-manager-osc[5300]: time="2021-07-07T14:25:26Z" level=warning msg="Could not find a master in topology" cluster=Default code=ERR00012 status=RESOLV type=state
Jul 07 14:25:26 bmm-4 replication-manager-osc[5300]: time="2021-07-07T14:25:26Z" level=warning msg="No semisync settings on slave bmm-3:3306" cluster=Default code=WARN0048 status=OPENED type=state
Jul 07 14:25:26 bmm-4 replication-manager-osc[5300]: time="2021-07-07T14:25:26Z" level=warning msg="No log of replication queries in slow query on slave bmm-3:3306" cluster=Default code=WARN0054 status=OPENED type=state
Jul 07 14:25:26 bmm-4 replication-manager-osc[5300]: time="2021-07-07T14:25:26Z" level=warning msg="Master is unreachable but slaves are replicating" cluster=Default code=ERR00016 status=OPENED type=state
Jul 07 14:25:28 bmm-4 replication-manager-osc[5300]: panic: runtime error: invalid memory address or nil pointer dereference
Jul 07 14:25:28 bmm-4 replication-manager-osc[5300]: [signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x160302a]
Jul 07 14:25:28 bmm-4 replication-manager-osc[5300]: goroutine 94 [running]:
Jul 07 14:25:28 bmm-4 replication-manager-osc[5300]: github.com/signal18/replication-manager/cluster.(*Cluster).MonitorSchema(0xc0005c7980)
Jul 07 14:25:28 bmm-4 replication-manager-osc[5300]:         /var/jenkins_home/workspace/go/src/github.com/signal18/replication-manager/cluster/cluster.go:793 +0xca
Jul 07 14:25:28 bmm-4 replication-manager-osc[5300]: created by github.com/signal18/replication-manager/cluster.(*Cluster).Run
Jul 07 14:25:28 bmm-4 replication-manager-osc[5300]:         /var/jenkins_home/workspace/go/src/github.com/signal18/replication-manager/cluster/cluster.go:426 +0x705
``` 

until I remove the password on the other instances, replication-manager keept crashing.

my configuration is the following
```
root@bmm-4:~# cat /etc/replication-manager/config.toml
[Default]

title = "ClusterTest"
db-servers-hosts = "bmm-1:3306,bmm-2:3306,bmm-3:3306"
db-servers-credential = "repl-manager:foobar"
replication-credential = "repl:xxxxxxx"
replication-use-ssl = true
failover-mode = "manual"
```

**Comment by svaroqui** [comment]
Hi thanks for reporting this edge case that is probably due to wrong User definition in the mariadb nodes 

The Crash append in  this Schema monitor function 
```
func (cluster *Cluster) MonitorSchema() {
	if !cluster.Conf.MonitorSchemaChange {
		return
	}
       if !cluster.Conf.MonitorSchemaChange {
		return
	}
	if cluster.master == nil {
		return
	}
	if cluster.master.State == stateFailed || cluster.master.State == stateMaintenance {
		return
	}
	cluster.sme.SetMonitorSchemaState()
	cluster.master.Conn.SetConnMaxLifetime(3595 * time.Second)
```
I think that's probably because the state of the master was unconnected and the master was auto discovered from the slave but yet does not have a pool of connection . 

I'll see what i can do to strengthen the code here , i 'll keep you posted
