### ISSUE TITLE
v2.0.2 http frequent js errors

### ISSUE THREAD

**Issue by lenovore** [signal18/replication-manager#381]
Please fix this problem for version 2.0.x

![QQ截图20210913175957](https://user-images.githubusercontent.com/29646774/133064980-058a19b1-3ffd-405f-a2f6-f84764ac1c3c.png)

angular.min.js:108 Error: [$resource:badcfg] http://errors.angularjs.org/1.4.10/$resource/badcfg?p0=query&p1=array&p2=object&p3=GET&p4=%2Fagents
    at angular.min.js:6
    at angular-resource.min.js:10
    at angular.min.js:120
    at n.$eval (angular.min.js:135)
    at n.$digest (angular.min.js:132)
    at n.$apply (angular.min.js:135)
    at g (angular.min.js:88)
    at S (angular.min.js:92)
    at XMLHttpRequest.t.onload (angular.min.js:93)
(anonymous) @ angular.min.js:108
(anonymous) @ angular.min.js:81
(anonymous) @ angular.min.js:121
$eval @ angular.min.js:135
$digest @ angular.min.js:132
$apply @ angular.min.js:135
g @ angular.min.js:88
S @ angular.min.js:92
t.onload @ angular.min.js:93
load (async)
(anonymous) @ angular.min.js:93
n @ angular.min.js:90
g @ angular.min.js:87
(anonymous) @ angular.min.js:120
$eval @ angular.min.js:135
$digest @ angular.min.js:132
$apply @ angular.min.js:135
(anonymous) @ angular.min.js:97

angular.min.js:108 Error: [$parse:syntax] http://errors.angularjs.org/1.4.10/$parse/syntax?p0=%3A&p1=is%20an%20unexpected%20token&p2=6&p3=width%3A400&p4=%3A400
    at http://172.16.20.186:8080/static/vendor/angular.min.js:6:417
    at s.throwError (http://172.16.20.186:8080/static/vendor/angular.min.js:214:470)
    at s.ast (http://172.16.20.186:8080/static/vendor/angular.min.js:207:209)
    at sd.compile (http://172.16.20.186:8080/static/vendor/angular.min.js:216:329)
    at gc.parse (http://172.16.20.186:8080/static/vendor/angular.min.js:243:303)
    at c (http://172.16.20.186:8080/static/vendor/angular.min.js:115:333)
    at b.$watch (http://172.16.20.186:8080/static/vendor/angular.min.js:129:109)
    at http://172.16.20.186:8080/static/vendor/angular.min.js:287:313
    at ea (http://172.16.20.186:8080/static/vendor/angular.min.js:74:16)
    at w (http://172.16.20.186:8080/static/vendor/angular.min.js:61:340) <table ng-if="servers" class="table ng-scope" ng-style="width:400">

**Comment by lenovore** [comment]
![2](https://user-images.githubusercontent.com/29646774/133065569-7f84a24d-ab95-43b0-8307-0764d5cc0870.png)

**Comment by tanji** [comment]
Hi @lenovore we are not AngularJS experts, feel free to submit a PR to fix the issue.
Also 2.0.x is EOL
